Repository tukcomCD2024/Code-Bridge, pull requests merged in 2024-01, with the labels that each got.

#17 feat : 로그인/회원가입
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/entity/Organization.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/controller/UserController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/dto/UserLoginDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/repository/UserRepository.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/service/UserService.java
Labels: ✨ Feature

#19 feat: 페이지 디자인
  frontend/.gitignore
  frontend/README.md
  frontend/frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/Component/Mainpage/Header.js
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/User/LoginPage.js
  frontend/src/Component/User/SignupPage.js
  frontend/src/image/NoneImage.png
  frontend/src/image/NoneImage2.png
  frontend/src/image/addNote.svg
  frontend/src/image/dragon.png
  frontend/src/image/googleLoginBtn.png
  frontend/src/image/logo.png
  frontend/src/index.js
  frontend/src/styles.css
Labels: 🎨 Design

#21 Backend#18/organzation crud
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/NoteController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/OrganizationController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/entity/Organization.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/notedto/NoteCreateDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/notedto/NoteDeleteDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/notedto/NoteUpdateDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/organdto/OrganizationCreateDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/organdto/OrganizationDeleteDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/organdto/OrganizationUpdateDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/repository/NoteRepository.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/repository/PageRepository.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/NoteService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/OrganizationService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/entity/Users.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/service/UserService.java
Labels: ✨ Feature

#24 feat : 이미지 업로드
  backend/shareNote/.gitignore
  backend/shareNote/build.gradle
  backend/shareNote/docker-compose.yml
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/S3/S3Controller.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/S3/S3ImageDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/S3/S3UploadService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/config/S3Config.java
  backend/shareNote/src/main/resources/application.yml
Labels: ⚙ Setting, ✨ Feature
