Repository tukcomCD2024/Code-Bridge, pull requests merged in 2024-05, with the labels that each got.

#188 Frontend#185/페이지 동작 퍼블리싱, 웹뷰에서 에디터에 이미지 업로드하기 위한 데모 코드 적용
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
Labels: ✨ Feature

#196 Frontend#189/코드 수정, 노트 생성 시 초기 메인 페이지 동시 생성
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
Labels: 🔨 Refactor

#205 Frontend#201/좋아요 퍼블리싱
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
  frontend/src/Component/Page/utils/pageSettings.js
Labels: ✨ Feature

#208 Frontend#206/에디터에서 이미지 세로 길이 제한, 이미지 더블클릭으로 원본 크기의 이미지 표시
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/ProseMirror_css/prosemirror_image_plugin/common.css
  frontend/src/Component/Page/ProseMirror_css/prosemirror_image_plugin/withResize.css
  frontend/src/Component/Page/utils/ModalImageComponent.js
Labels: ✨ Feature

#210 Frontend#209/모바일 환경에서 에디터 CSS 최적화
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
Labels: 🎨 Design

#214 Frontend#213/모바일 환경에서 글 작성 시작 위치를 동적 변경
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
  frontend/src/setupProxy.js
Labels: ✨ Feature

#226 Frontend#217/코드 리팩토링
  frontend/src/Component/Mainpage/OrganizationDetails.js
  frontend/src/Component/Note/NoteDetail.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Note/organizationInfo/organizationInfo.js
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/utils/editor/ImageToEditor.js
  frontend/src/Component/Page/utils/editor/ModalImageComponent.js
  frontend/src/Component/Page/utils/editor/checkBlockType.js
  frontend/src/Component/Page/utils/editor/noteSettingModal.js
  frontend/src/Component/Page/utils/editor/pageSettings.js
  frontend/src/Component/Page/utils/editor/plugin/generateBlockIdPlugin.js
  frontend/src/Component/Page/utils/editor/plugin/hoverButtonPlugin.js
  frontend/src/Component/Page/utils/editor/plugin/inlinePlaceholderPlugin.js
  frontend/src/Component/Page/utils/initMobileWebView.js
  frontend/src/Component/Page/utils/navigationBar/ModalImageComponent.js
  frontend/src/Component/Page/utils/pageSettings.js
  frontend/src/Component/Page/utils/yjs/BlockLike.js
  frontend/src/Component/Page/utils/yjs/BlockLock.js
  frontend/src/Component/Page/utils/yjs/YjsInstances.js
  frontend/src/Component/Utils/formatCreationTime.js
  frontend/src/Component/Utils/imageToBackend.js
Labels: 🔨 Refactor

#228 Backend#225/quiz
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/DTOs/quizdto/QuizCreateDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/DTOs/quizdto/QuizDeleteDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/DTOs/quizdto/QuizDetailReqDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/DTOs/quizdto/QuizDetailResDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/DTOs/quizdto/QuizSearchDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/DTOs/quizdto/QuizSolveDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/QuizController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/entity/Organization.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/repository/QuizRepository.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/NoteService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/OrganizationService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/QuizService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Quiz/entity/Quiz.java
  nodejs/server.js
Labels: ✨ Feature

#230 Backend#229/contribution
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/DTOs/contributiondto/ContributionResultDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/ContributeController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/entity/Organization.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/ContributionService.java
  frontend/src/Component/Page/utils/editor/plugin/generateBlockIdPlugin.js
  nodejs/server.js
Labels: ✨ Feature, 🔨 Refactor

#232 Frontend#227/잠금 기능 개선, 코드 오류 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/utils/editor/ImageToEditor.js
  frontend/src/Component/Page/utils/editor/pageSettings.js
  frontend/src/Component/Page/utils/editor/plugin/generateBlockIdPlugin.js
  frontend/src/Component/Page/utils/editor/plugin/hoverButtonPlugin.js
  frontend/src/Component/Page/utils/editor/plugin/inlinePlaceholderPlugin.js
  frontend/src/Component/Page/utils/yjs/BlockLock.js
  frontend/src/Component/Page/utils/yjs/YjsInstances.js
Labels: 🐞 Error, ✨ Feature, 🔨 Refactor
