Repository tukcomCD2024/Code-Bridge, pull requests merged in 2024-03, with the labels that each got.

#92 feat: 여러 개 이슈 해결
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/Component/Auth/LoginPage.js
  frontend/src/Component/Auth/UserProfileEdit.js
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Note/organizationInfo/organizationInfo.js
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
  frontend/src/image/loading.gif
  frontend/src/index.js
  frontend/src/styles.css
Labels: ✨ Feature, 🔨 Refactor

#95 feat: Organization 데이터 불러오기
  frontend/public/index.html
  frontend/src/Component/Auth/LoginPage.js
  frontend/src/Component/Mainpage/Header.js
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Note/organizationInfo/organizationInfo.js
  frontend/src/styles.css
Labels: ✨ Feature

#98 feat: Organization 노트 데이터 받아오기
  frontend/src/App.js
  frontend/src/Component/Auth/AuthPage.js
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Page/Page.js
  frontend/src/index.js
Labels: ✨ Feature

#100 feat: 노트 데이터 불러오기
  frontend/src/Component/Auth/AuthPage.js
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/imageToBackend.js
Labels: ✨ Feature

#102 feat: 로그인 화면에서 사용자 알림 표시(+ 초대 관련 이메일 전송 기능 동작)
  frontend/src/Component/Auth/LoginPage.js
  frontend/src/Component/Note/organizationInfo/organizationInfo.js
Labels: ✨ Feature

#111 feat: organization 이메일 초대
  frontend/src/App.js
  frontend/src/Component/Auth/AuthPage.js
  frontend/src/Component/Auth/LoginPage.js
  frontend/src/Component/Utils/EmailTokenHandler.js
Labels: ✨ Feature

#117 Backend#105/https설정2
  .github/workflows/githubAction.yml
  .idea/.gitignore
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/config/WebConfig.java
  frontend/dockerfile
  frontend/nginx.conf
  frontend/src/setupProxy.js
Labels: ⚙ Setting, 🌏 배포

#118 frontend#116/에디터(페이지)에서 기능 개발 및 코드 수정
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
  frontend/src/Component/Utils/cursorColor.js
Labels: ✨ Feature, 🔨 Refactor

#128 Frontend#125/에디터 네비게이션바 정보 표시 및 코드 일부 수정
  frontend/src/App.js
  frontend/src/Component/Auth/SignupPage.js
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Note/organizationInfo/organizationInfo.js
  frontend/src/Component/Page/Page.js
  frontend/src/image/addNote.svg
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#131 feat: 페이지(에디터) 네비게이션바 화면 수정
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/utils/inlinePlaceholderPlugin.js
Labels: ✨ Feature

#141 Frontend#135/노드(블록)에 고유 ID(UUID) 부여
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/utils/YjsInstance.js
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
  frontend/src/Component/Page/utils/pageSettings.js
Labels: ✨ Feature

#143 Frontend#142/노드 편집 잠금 적용
  frontend/public/index.html
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
  frontend/src/Component/Page/utils/pageSettings.js
  frontend/src/image/lock2.gif
Labels: ✨ Feature

#145 Frontend#144/노드 편집 잠금 개선
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
Labels: ✨ Feature
