Repository tukcomCD2024/Code-Bridge, pull requests merged in 2024-02, with the labels that each got.

#29 Backend#25/page+cors
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/PageController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/entity/Organization.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/pagedto/PageCreateDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/pagedto/PageDeleteDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/OrganizationService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/PageService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/dto/UserLoginDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/dto/UserSignUpDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/entity/Users.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/repository/UserRepository.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/service/UserService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/config/WebConfig.java
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor

#32 feat: 초기 진입 페이지 생성 및 일부 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/Component/Auth/AuthPage.js
  frontend/src/Component/Auth/LoginPage.js
  frontend/src/Component/Auth/SignupPage.js
  frontend/src/Component/Mainpage/Header.js
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Mainpage/OrganizationDetails.js
  frontend/src/Component/imageToBackend.js
  frontend/src/image/book1.gif
  frontend/src/image/veryBigEye.gif
Labels: ✨ Feature, 🎨 Design

#36 design: 웹페이지 외부 폰트 및 이모지 적용
  frontend/src/styles.css
Labels: 🎨 Design

#38 feat: 노트 화면 퍼블리싱
  frontend/src/App.js
  frontend/src/Component/Auth/LoginPage.js
  frontend/src/Component/Auth/SignupPage.js
  frontend/src/Component/Mainpage/Header.js
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Mainpage/OrganizationDetails.js
  frontend/src/Component/Note/NoteDetail.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Utils/formatCreationTime.js
  frontend/src/image/camera_icon.png
  frontend/src/index.js
Labels: ✨ Feature, 🎨 Design

#47 Backend#46/rabbit web socket docker
  backend/shareNote/build.gradle
  backend/shareNote/docker-compose.yml
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/NoteController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/OrganizationController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/PageController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/User/controller/UserController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/config/RabbitConfig.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/config/StompConfig.java
  backend/shareNote/src/main/resources/application.yml
Labels: ⚙ Setting

#51 feat: 로그인, 회원가입 백엔드와 통신
  frontend/src/Component/Auth/LoginPage.js
  frontend/src/Component/Auth/SignupPage.js
Labels: ✨ Feature

#52 feat: 회원정보변경 페이지 디자인
  frontend/src/App.js
  frontend/src/Component/Auth/UserProfileEdit.js
  frontend/src/Component/Mainpage/Header.js
  frontend/src/image/logo_person.gif
  frontend/src/image/notion.png
Labels: 🔨 Refactor, 🎨 Design

#58 feat: 이미지 백엔드로 업로드 후 S3 URL 받기
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Utils/emojiList.js
  frontend/src/Component/imageToBackend.js
Labels: ✨ Feature, 🎨 Design

#61 feat: 텍스트 및 이미지 에디터 초기적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Component/Auth/SignupPage.js
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/ProseMirror_css/image/common.css
  frontend/src/Component/Page/ProseMirror_css/image/sideResize.css
  frontend/src/Component/Page/ProseMirror_css/image/withResize.css
  frontend/src/Component/Page/ProseMirror_css/image/withoutResize.css
Labels: ✨ Feature

#65 Backend#63/텍스트입력api
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Block/controller/BlockTestController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Block/dto/BlockDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Block/dto/ContentDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Block/dto/PageBlocksDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Block/entity/Block.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Block/repository/BlockRepository.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Block/service/BlockService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/NoteController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/OrganizationController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/PageController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/controller/StompPageController.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/entity/Organization.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/notedto/NoteSearchDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/organdto/OrganizationCreateDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/organdto/OrganizationSearchDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/pagedto/PageSearchDTO.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/NoteService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/OrganizationService.java
  backend/shareNote/src/main/java/com/Backend/shareNote/domain/Oraganization/service/PageService.java
Labels: ✨ Feature

#66 feat: 노트 블록(노드)마다 작은 메뉴창 표시
  frontend/src/Component/Auth/AuthPage.js
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/checkBlockType.js
  frontend/src/image/down.gif
  frontend/src/image/down_arrow.svg
  frontend/src/image/plus_icon.svg
  frontend/src/image/typing.gif
  frontend/src/index.js
  frontend/src/styles.css
Labels: ✨ Feature, 🎨 Design

#72 feat: ResizeObserver 에러 + 노트 블록(노드)의 placeholder 리팩토링
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/checkBlockType.js
Labels: 🐞 Error, 🔨 Refactor

#79 feat: 노드 메뉴창 위치 에러 해결
  .idea/vcs.xml
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/checkBlockType.js
Labels: 🐞 Error

#82 feat: 일부 페이지 디테일 추가
  frontend/src/Component/Auth/UserProfileEdit.js
  frontend/src/Component/Note/NotePage.js
Labels: 🎨 Design

#86 feat: page.js 코드 분리(간소화)
  frontend/src/Component/Page/Page.js
  frontend/src/Component/Page/ProseMirror_css/ProseMirror.css
  frontend/src/Component/Page/ProseMirror_css/prosemirror_image_plugin/common.css
  frontend/src/Component/Page/ProseMirror_css/prosemirror_image_plugin/sideResize.css
  frontend/src/Component/Page/ProseMirror_css/prosemirror_image_plugin/withResize.css
  frontend/src/Component/Page/ProseMirror_css/prosemirror_image_plugin/withoutResize.css
  frontend/src/Component/Page/utils/YjsInstance.js
  frontend/src/Component/Page/utils/checkBlockType.js
  frontend/src/Component/Page/utils/hoverButtonPlugin.js
  frontend/src/Component/Page/utils/inlinePlaceholderPlugin.js
  frontend/src/Component/Page/utils/pageSettings.js
Labels: 🔨 Refactor

#87 feat: Organization 정보 확인 모달창 구현
  frontend/src/Component/Mainpage/MainPage.js
  frontend/src/Component/Note/NotePage.js
  frontend/src/Component/Note/organizationInfo/organizationInfo.js
  frontend/src/toastr_information.txt
Labels: ✨ Feature, 🎨 Design
